export var globalroles = [
    { "title": "dashboard", "page": "Dashboard","canView":false },
    { "title": "Supplier", "page": "Supplier","canAdd":false,"canUpdate":false,"canDelete":false,"canView":false,"canViewDetail":false },
    { "title": "Contract", "page": "ContractItem","canAdd":false,"canUpdate":false,"canDelete":false,"canView":false },
    { "title": "contract Extension", "page": "ContractExtension","canAdd":false,"canUpdate":false,"canDelete":false,"canView":false },
    { "title": "Area", "page": "Area","canAdd":false,"canUpdate":false,"canDelete":false,"canView":false },
    { "title": "Categories", "page": "Category","canAdd":false,"canUpdate":false,"canDelete":false,"canView":false },
    { "title": "Warehouse", "page": "Warehouse","canAdd":false,"canUpdate":false,"canDelete":false,"canView":false },
    { "title": "Store", "page": "Store","canAdd":false,"canUpdate":false,"canDelete":false,"canView":false },
    { "title": "Inventory", "page": "Inventory","canAdd":false,"canUpdate":false,"canDelete":false,"canView":false },
    { "title": "Product", "page": "Product","canAdd":false,"canUpdate":false,"canDelete":false,"canView":false },
    { "title": "Product Variant", "page": "Item","canAdd":false,"canUpdate":false,"canDelete":false,"canView":false },
    { "title": "Product Variant Option", "page": "Option","canAdd":false,"canUpdate":false,"canDelete":false,"canView":false },
    { "title": "Orders", "page": "Order","canAdd":false,"canUpdate":false,"canDelete":false,"canView":false,"canViewDetail":false },
    { "title": "System User", "page": "System","canAdd":false,"canUpdate":false,"canDelete":false,"canView":false },
    { "title": "Client", "page": "Client","canAdd":false,"canUpdate":false,"canDelete":false,"canView":false,"canViewDetail":false },
    { "title": "Group & Role", "page": "Group","canAdd":false,"canUpdate":false,"canDelete":false,"canView":false },
    { "title": "Content", "page": "Content","canAdd":false,"canUpdate":false,"canDelete":false,"canView":false },
    { "title": "Lookups", "page": "Lookup","canAdd":false,"canUpdate":false,"canDelete":false,"canView":false },
    { "title": "Setting", "page": "Setting","canAdd":false,"canUpdate":false,"canDelete":false,"canView":false },
    { "title": "Packages", "page": "Package","canAdd":false,"canUpdate":false,"canDelete":false,"canView":false },
    { "title": "Payment", "page": "Payment","canAdd":false,"canUpdate":false,"canDelete":false,"canView":false,"canViewDetail":false },
    { "title": "Bank Account", "page": "Bank","canAdd":false,"canUpdate":false,"canDelete":false,"canView":false },
    { "title": "Feedback and Complain", "page": "Feedback","canAdd":false,"canUpdate":false,"canDelete":false,"canView":false,"canViewDetail":false },
    { "title": "Report", "page": "Report","canAdd":false,"canUpdate":false,"canDelete":false,"canView":false },
    { "title": "Language", "page": "Language","canAdd":false,"canUpdate":false,"canDelete":false,"canView":false }
  ];